include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    # - "**/main_*.dart"
  errors:
    unused_local_variable: warning
    invalid_assignment: warning
    invalid_annotation_target: ignore
    missing_return: error
    annotate_overrides: error
    todo: info

linter:
  rules:
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_void_async: true
    unawaited_futures: true
    await_only_futures: true
    unnecessary_await_in_return: true
